### ISSUE TITLE
Don't bundle the Jitsi Meet external API module

### ISSUE THREAD

**Issue by saghul** [IssabelFoundation/extras#1]
I see the meet extra currently bundles the external_api.js module: https://github.com/IssabelFoundation/extras/blob/master/modules/meet/themes/default/js/external_api.js

This is not a good idea because we may make small backwards compatible improvements that Issabel would be missing out on. In addition, any change to the message bus would result in a failure.

@asternic can you please load it dynamically?

**Comment by asternic** [comment]
Done!

**Comment by saghul** [comment]
Thanks! ❤️
